# Generated by Django 3.1.1 on 2020-10-02 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='year',
            field=models.IntegerField(),
        ),
    ]
