# Generated by Django 3.1.1 on 2020-10-02 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('unesco', '0002_auto_20201002_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sites',
            name='area_hectares',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sites',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
